graph TD
    N0[activate_this.py]
    N1[jp.py]
    N2[greenlet.h]
    N3[__init__.py]
    N4[config_analyzer.py]
    N5[main.py]
    N6[bootstrap.js]
    N7[imageMapResizer.min.js]
    N8[jquery-2.1.0.min.js]
    N9[jquery.bonsai.js]
    N10[less-1.7.0.min.js]
    N11[1_generate_skill.py]
    N12[2_upload_to_chroma.py]
    N13[3_query_example.py]
    N14[generate_clinerules.py]
    N15[context_server.py]
    N16[quickstart.py]
    N17[App.tsx]
    N18[index.tsx]
    N19[generate_cursorrules.py]
    N20[1_generate_skill.py]
    N21[2_build_faiss_index.py]
    N22[3_query_example.py]
    N23[quickstart.py]
    N24[quickstart.py]
    N25[quickstart.py]
    N26[quickstart.py]
    N27[1_generate_skill.py]
    N28[2_upload_to_qdrant.py]
    N29[3_query_example.py]
    N30[test_http_server.py]
    N31[1_generate_skill.py]
    N32[2_upload_to_weaviate.py]
    N33[3_query_example.py]
    N34[generate_windsurfrules.py]
    N35[translate_doc.py]
    N36[__init__.py]
    N37[_version.py]
    N38[__init__.py]
    N39[framework.py]
    N40[models.py]
    N41[runner.py]
    N42[__init__.py]
    N43[__init__.py]
    N44[base.py]
    N45[chroma.py]
    N46[claude.py]
    N47[deepseek.py]
    N48[faiss_helpers.py]
    N49[fireworks.py]
    N50[gemini.py]
    N51[haystack.py]
    N52[ibm_bob.py]
    N53[kimi.py]
    N54[langchain.py]
    N55[llama_index.py]
    N56[markdown.py]
    N57[minimax.py]
    N58[openai.py]
    N59[openai_compatible.py]
    N60[opencode.py]
    N61[openrouter.py]
    N62[pinecone_adaptor.py]
    N63[qdrant.py]
    N64[qwen.py]
    N65[streaming_adaptor.py]
    N66[together.py]
    N67[weaviate.py]
    N68[agent_client.py]
    N69[ai_enhancer.py]
    N70[api_reference_builder.py]
    N71[architectural_pattern_detector.py]
    N72[__init__.py]
    N73[analyze.py]
    N74[asciidoc.py]
    N75[chat.py]
    N76[common.py]
    N77[confluence.py]
    N78[create.py]
    N79[enhance.py]
    N80[epub.py]
    N81[github.py]
    N82[html.py]
    N83[jupyter.py]
    N84[manpage.py]
    N85[notion.py]
    N86[openapi.py]
    N87[package.py]
    N88[pdf.py]
    N89[pptx.py]
    N90[rss.py]
    N91[scrape.py]
    N92[sync_config.py]
    N93[unified.py]
    N94[upload.py]
    N95[video.py]
    N96[word.py]
    N97[workflow.py]
    N98[asciidoc_scraper.py]
    N99[benchmark_cli.py]
    N100[browser_renderer.py]
    N101[chat_scraper.py]
    N102[cloud_storage_cli.py]
    N103[code_analyzer.py]
    N104[codebase_scraper.py]
    N105[config_command.py]
    N106[config_enhancer.py]
    N107[config_extractor.py]
    N108[config_fetcher.py]
    N109[config_manager.py]
    N110[config_validator.py]
    N111[conflict_detector.py]
    N112[confluence_scraper.py]
    N113[constants.py]
    N114[create_command.py]
    N115[defaults.py]
    N116[dependency_analyzer.py]
    N117[doc_scraper.py]
    N118[doctor.py]
    N119[embedding_pipeline.py]
    N120[enhance_command.py]
    N121[enhance_skill.py]
    N122[enhance_skill_local.py]
    N123[enhance_status.py]
    N124[enhancement_workflow.py]
    N125[epub_scraper.py]
    N126[estimate_pages.py]
    N127[execution_context.py]
    N128[generate_router.py]
    N129[github_fetcher.py]
    N130[github_scraper.py]
    N131[guide_enhancer.py]
    N132[how_to_guide_builder.py]
    N133[html_scraper.py]
    N134[incremental_updater.py]
    N135[install_agent.py]
    N136[install_skill.py]
    N137[jupyter_scraper.py]
    N138[language_detector.py]
    N139[llms_txt_detector.py]
    N140[llms_txt_downloader.py]
    N141[llms_txt_parser.py]
    N142[main.py]
    N143[man_scraper.py]
    N144[markdown_cleaner.py]
    N145[merge_sources.py]
    N146[multilang_support.py]
    N147[notion_scraper.py]
    N148[openapi_scraper.py]
    N149[opencode_skill_splitter.py]
    N150[package_multi.py]
    N151[package_skill.py]
    N152[__init__.py]
    N153[analyze_parser.py]
    N154[asciidoc_parser.py]
    N155[base.py]
    N156[chat_parser.py]
    N157[config_parser.py]
    N158[confluence_parser.py]
    N159[create_parser.py]
    N160[doctor_parser.py]
    N161[enhance_parser.py]
    N162[enhance_status_parser.py]
    N163[epub_parser.py]
    N164[estimate_parser.py]
    N165[__init__.py]
    N166[base_parser.py]
    N167[formatters.py]
    N168[markdown_parser.py]
    N169[pdf_parser.py]
    N170[quality_scorer.py]
    N171[rst_parser.py]
    N172[unified_structure.py]
    N173[github_parser.py]
    N174[html_parser.py]
    N175[install_agent_parser.py]
    N176[install_parser.py]
    N177[jupyter_parser.py]
    N178[manpage_parser.py]
    N179[multilang_parser.py]
    N180[notion_parser.py]
    N181[openapi_parser.py]
    N182[package_parser.py]
    N183[pdf_parser.py]
    N184[pptx_parser.py]
    N185[quality_parser.py]
    N186[resume_parser.py]
    N187[rss_parser.py]
    N188[scan_parser.py]
    N189[scrape_parser.py]
    N190[stream_parser.py]
    N191[sync_config_parser.py]
    N192[test_examples_parser.py]
    N193[unified_parser.py]
    N194[update_parser.py]
    N195[upload_parser.py]
    N196[video_parser.py]
    N197[word_parser.py]
    N198[workflows_parser.py]
    N199[pattern_recognizer.py]
    N200[pdf_extractor_poc.py]
    N201[pdf_scraper.py]
    N202[pptx_scraper.py]
    N203[__init__.py]
    N204[analyze_presets.py]
    N205[github_presets.py]
    N206[manager.py]
    N207[scrape_presets.py]
    N208[quality_checker.py]
    N209[quality_metrics.py]
    N210[rag_chunker.py]
    N211[rate_limit_handler.py]
    N212[resume_command.py]
    N213[rss_scraper.py]
    N214[run_tests.py]
    N215[scan_command.py]
    N216[setup_wizard.py]
    N217[signal_collectors.py]
    N218[signal_flow_analyzer.py]
    N219[skill_converter.py]
    N220[source_detector.py]
    N221[split_config.py]
    N222[__init__.py]
    N223[azure_storage.py]
    N224[base_storage.py]
    N225[gcs_storage.py]
    N226[s3_storage.py]
    N227[streaming_ingest.py]
    N228[swift_patterns.py]
    N229[sync_cli.py]
    N230[sync_config.py]
    N231[test_example_extractor.py]
    N232[test_unified_simple.py]
    N233[unified_codebase_analyzer.py]
    N234[unified_enhancer.py]
    N235[unified_scraper.py]
    N236[unified_skill_builder.py]
    N237[upload_skill.py]
    N238[utils.py]
    N239[video_metadata.py]
    N240[video_models.py]
    N241[video_scraper.py]
    N242[video_segmenter.py]
    N243[video_setup.py]
    N244[video_transcript.py]
    N245[video_visual.py]
    N246[word_scraper.py]
    N247[workflow_runner.py]
    N248[workflows_command.py]
    N249[__init__.py]
    N250[cache.py]
    N251[generator.py]
    N252[models.py]
    N253[server.py]
    N254[__init__.py]
    N255[agent_detector.py]
    N256[config_publisher.py]
    N257[git_repo.py]
    N258[marketplace_manager.py]
    N259[marketplace_publisher.py]
    N260[server.py]
    N261[server_fastmcp.py]
    N262[server_legacy.py]
    N263[source_manager.py]
    N264[__init__.py]
    N265[config_tools.py]
    N266[marketplace_tools.py]
    N267[packaging_tools.py]
    N268[scraping_tools.py]
    N269[source_tools.py]
    N270[splitting_tools.py]
    N271[sync_config_tools.py]
    N272[vector_db_tools.py]
    N273[workflow_tools.py]
    N274[__init__.py]
    N275[detector.py]
    N276[models.py]
    N277[monitor.py]
    N278[notifier.py]
    N279[__init__.py]
    N280[__init__.py]
    N281[conftest.py]
    N282[generate_fixtures.py]
    N283[test_adaptor_benchmarks.py]
    N284[__init__.py]
    N285[test_adaptors_e2e.py]
    N286[test_base.py]
    N287[test_chroma_adaptor.py]
    N288[test_claude_adaptor.py]
    N289[test_faiss_adaptor.py]
    N290[test_gemini_adaptor.py]
    N291[test_haystack_adaptor.py]
    N292[test_ibm_bob_adaptor.py]
    N293[test_langchain_adaptor.py]
    N294[test_llama_index_adaptor.py]
    N295[test_markdown_adaptor.py]
    N296[test_minimax_adaptor.py]
    N297[test_openai_adaptor.py]
    N298[test_openai_compatible_base.py]
    N299[test_openai_compatible_shared.py]
    N300[test_opencode_adaptor.py]
    N301[test_qdrant_adaptor.py]
    N302[test_weaviate_adaptor.py]
    N303[test_agent_client.py]
    N304[test_api_reference_builder.py]
    N305[test_architectural_pattern_detector.py]
    N306[test_architecture_scenarios.py]
    N307[test_async_scraping.py]
    N308[test_benchmark.py]
    N309[test_bootstrap_skill.py]
    N310[test_bootstrap_skill_e2e.py]
    N311[test_browser_renderer.py]
    N312[test_c3_integration.py]
    N313[test_chunking_integration.py]
    N314[test_cli_parsers.py]
    N315[test_cli_paths.py]
    N316[test_cli_refactor_e2e.py]
    N317[test_cloud_storage.py]
    N318[test_code_analyzer.py]
    N319[test_codebase_scraper.py]
    N320[test_config_extractor.py]
    N321[test_config_fetcher.py]
    N322[test_config_publisher.py]
    N323[test_config_validation.py]
    N324[test_conflict_detector.py]
    N325[test_constants.py]
    N326[test_create_arguments.py]
    N327[test_create_integration_basic.py]
    N328[test_dependency_analyzer.py]
    N329[test_docker_smoke.py]
    N330[test_doctor.py]
    N331[test_e2e_three_stream_pipeline.py]
    N332[test_embedding.py]
    N333[test_embedding_pipeline.py]
    N334[test_embedding_server.py]
    N335[test_encoding.py]
    N336[test_enhance_command.py]
    N337[test_enhance_skill_local.py]
    N338[test_epub_scraper.py]
    N339[test_estimate_pages.py]
    N340[test_excluded_dirs_config.py]
    N341[test_execution_context.py]
    N342[test_framework_detection.py]
    N343[test_generate_router_github.py]
    N344[test_git_repo.py]
    N345[test_git_sources_e2e.py]
    N346[test_github_fetcher.py]
    N347[test_github_scraper.py]
    N348[test_guide_enhancer.py]
    N349[test_how_to_guide_builder.py]
    N350[test_incremental_updates.py]
    N351[test_install_agent.py]
    N352[test_install_multiplatform.py]
    N353[test_install_skill.py]
    N354[test_install_skill_e2e.py]
    N355[test_integration.py]
    N356[test_integration_adaptors.py]
    N357[test_issue_219_e2e.py]
    N358[test_issue_277_discord_e2e.py]
    N359[test_issue_277_real_world.py]
    N360[test_kotlin_support.py]
    N361[test_language_detector.py]
    N362[test_large_inputs.py]
    N363[test_llms_txt_downloader.py]
    N364[test_markdown_parsing.py]
    N365[test_marketplace_manager.py]
    N366[test_marketplace_publisher.py]
    N367[test_mcp_fastmcp.py]
    N368[test_mcp_git_sources.py]
    N369[test_mcp_server.py]
    N370[test_mcp_vector_dbs.py]
    N371[test_mcp_workflow_tools.py]
    N372[test_merge_sources_github.py]
    N373[test_multi_source.py]
    N374[test_multilang_support.py]
    N375[test_new_source_types.py]
    N376[test_opencode_skill_splitter.py]
    N377[test_package_skill.py]
    N378[test_package_structure.py]
    N379[test_parallel_scraping.py]
    N380[test_pattern_recognizer.py]
    N381[test_pdf_advanced_features.py]
    N382[test_pdf_extractor.py]
    N383[test_pdf_scraper.py]
    N384[test_pinecone_adaptor.py]
    N385[test_preset_system.py]
    N386[test_quality_checker.py]
    N387[test_quality_metrics.py]
    N388[test_rag_chunker.py]
    N389[test_rate_limit_handler.py]
    N390[test_real_world_fastmcp.py]
    N391[test_scan_command.py]
    N392[test_scrape_count.py]
    N393[test_scraper_features.py]
    N394[test_server_fastmcp_http.py]
    N395[test_setup_scripts.py]
    N396[test_signal_collectors.py]
    N397[test_skip_llms_txt.py]
    N398[test_smart_summarization.py]
    N399[test_source_detector.py]
    N400[test_source_manager.py]
    N401[test_streaming_ingestion.py]
    N402[test_swift_detection.py]
    N403[test_sync_config.py]
    N404[test_sync_config_e2e.py]
    N405[test_sync_detector.py]
    N406[test_sync_models.py]
    N407[test_sync_monitor.py]
    N408[test_sync_notifier.py]
    N409[test_terminal_detection.py]
    N410[test_test_example_extractor.py]
    N411[test_unified.py]
    N412[test_unified_analyzer.py]
    N413[test_unified_config_validator.py]
    N414[test_unified_mcp_integration.py]
    N415[test_unified_parsers.py]
    N416[test_unified_scraper_orchestration.py]
    N417[test_upload_integration.py]
    N418[test_upload_skill.py]
    N419[test_url_conversion.py]
    N420[test_utilities.py]
    N421[test_video_scraper.py]
    N422[test_video_setup.py]
    N423[test_word_scraper.py]
    N424[test_workflow_prompt_injection.py]
    N425[test_workflow_runner.py]
    N426[test_workflow_tools_mcp.py]
    N427[test_workflows_command.py]